@startuml sequence_diagram
actor User
participant FEService
participant BEService
participant AIAgent
database Database

== Init process ==
User -> FEService: access
FEService -> BEService: init data - API01
BEService -> AIAgent: AI request data
AIAgent --> BEService: AI response
BEService -> Database: store data
BEService --> FEService: fe data

== Draft schedule ==
User -> FEService: prompt
FEService -> BEService: modify data - API02
BEService -> Database: get store data
Database --> BEService: store data
BEService -> AIAgent: AI request data
AIAgent --> BEService: AI response data
BEService --> FEService: fe data
FEService --> User: Confirm

== Approval schedule ==
alt ok
  User -> FEService: OK
  FEService -> BEService: tasks resend
  BEService -> Database: store data(only update tasks)
  FEService -> User: rebuild using new data
else ng
  User -> FEService: NG
  FEService -> User: rebuild using old data
end

@enduml