name: Deploy Flutter Web to Cloud Run

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: i-crossbar-471511-h9
      REGION: asia-northeast1           # Cloud Run と Artifact Registry のリージョン
      REPO_NAME: dreamgenie-repo      # Artifact Registry のリポジトリ名
      IMAGE_NAME: dreamgenie-app       # Docker イメージ名
      SERVICE_NAME: dreamgenie-app         # Cloud Run サービス名

    steps:
    # 1. コードチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Flutter セットアップ
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'

    # 3. Flutter Web ビルド
    - name: Build Flutter Web
      working-directory: ./dream_genie
      run: flutter build web --release

    # 4. GCP 認証
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 5. Docker ビルド & プッシュ
    - name: Build and push Docker image
      run: |
        IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}
        echo "Building Docker image: $IMAGE_URI"
        docker build -t $IMAGE_URI ./dream_genie
        docker push $IMAGE_URI

    # 6. Cloud Run デプロイ
    - name: Deploy to Cloud Run
      run: |
        IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}
        echo "Deploying to Cloud Run: ${{ env.SERVICE_NAME }}"
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $IMAGE_URI \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated
