name: Deploy Flutter Web to Cloud Run

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: i-crossbar-471511-h9
      REGION: asia-northeast1           # Cloud Run と Artifact Registry のリージョン
      REPO_NAME: dreamgenie-repo      # Artifact Registry のリポジトリ名
      IMAGE_NAME: dreamgenie-app       # Docker イメージ名
      SERVICE_NAME: dreamgenie-app         # Cloud Run サービス名

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'

    - name: Build Flutter Web
      working-directory: ./dream_genie
      run: flutter build web --release

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        IMAGE_URI=asia-northeast1-docker.pkg.dev/i-crossbar-471511-h9/dreamgenie-repo/dreamgenie-app:latest
        docker build -t $IMAGE_URI ./dream_genie
        docker push $IMAGE_URI

    - name: Deploy to Cloud Run
      run: |
        IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        echo "Deploying to Cloud Run: ${{ env.SERVICE_NAME }}"
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image $IMAGE_URI \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated
